### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by HerozuKa** [rlzicar/Chessticle#2]
On the first launch when trying to connect, a connection error pops up. When we then select find a new opponent everything connects perfectly. Where to look for the error?

**Comment by rlzicar** [comment]
Thanks for bringing this to my attention. It seems like it was caused by certain changes in the latest version of PUN. It should be fixed now.

**Comment by HerozuKa** [comment]
> Thanks for bringing this to my attention. It seems like it was caused by certain changes in the latest version of PUN. It should be fixed now.

A piece of great work. Sincere greetings and gratitude for your quick response and help. Greetings
